### ISSUE TITLE
Translation consistency

### ISSUE THREAD

**Issue by larissa-n** [sasza2/react-arrows#9]
Related to [issue in /arrows](https://github.com/sasza2/arrows/issues/13):

Identical translation property will produce inconsistent arrow geometry -

<img width="759" alt="Screen Shot 2020-09-19 at 11 40 52 AM" src="https://user-images.githubusercontent.com/37840830/93720256-2e5a1100-fb88-11ea-8179-1d43c67cb13d.png">

https://codesandbox.io/s/strange-mahavira-hwfex?file=/src/App.js

**Comment by sasza2** [comment]
okay, thanks. fixed in newest version (1.1.0), should be visible on npm in a moment

https://codesandbox.io/s/solitary-voice-b2q9f

**Comment by larissa-n** [comment]
Great! Awesome how fast you were able to push the fix. Thank you!

<img width="300" alt="Screen Shot 2020-09-20 at 4 02 24 PM" src="https://user-images.githubusercontent.com/37840830/93721002-73347680-fb8d-11ea-9f82-107ee2cf16c6.png"> <img width="300" alt="Screen Shot 2020-09-20 at 4 03 48 PM" src="https://user-images.githubusercontent.com/37840830/93721005-7596d080-fb8d-11ea-9570-497ad1b20cda.png">

https://codesandbox.io/s/hopeful-flower-t9hgd?file=/src/App.js
